# -*- coding: utf-8 -*-
"""Assignment for day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1laT4PbPVNo0e3SCPu5cpct7FZiufuwfq
"""

a = 1000

b = 4500

c = 6500

a , b, c

a = 1000
print("safe to land")

if a < b :
  print("bring down to 1000")

if a > 6500 :
  print("bring down to 1000")
else:
  print("trun around")